[package]
name = "telegram_bot"
version = "0.1.0"
edition = "2021"

[dependencies]
teloxide = { version = "0.15.0", features = ["macros"] }
tokio = { version = "1.45.0", features = ["full"] }
serde_json = "1.0.140"
dotenv = "0.15.0"